### ISSUE TITLE
[BUG] Reference nested fields on field type validation causes unexpected error

### ISSUE THREAD

**Issue by fenos** [bufbuild/protovalidate-go#174]
## Description
When i try accessing a nested value from a field level validation using CEL, I get the following error:

```
compilation error: failed to compile expression coordinates: ERROR: <input>:1:6: unexpected failed resolution of 'google.type.LatLng'\n | (this.latitude < 90 && this.latitude > -90) &&(this.longitude < 180 && this.longitude > -90)\n | .....^\nERROR: <input>:1:28: unexpected failed resolution of 'google.type.LatLng'\n | (this.latitude < 90 && this.latitude > -90) &&(this.longitude < 180 && this.longitude > -90)\n | ...........................^\nERROR: <input>:1:52: unexpected failed resolution of 'google.type.LatLng'\n | (this.latitude < 90 && this.latitude > -90) &&(this.longitude < 180 && this.longitude > -90)\n | ...................................................^\nERROR: <input>:1:76: unexpected failed resolution of 'google.type.LatLng'\n | (this.latitude < 90 && this.latitude > -90) &&(this.longitude < 180 && this.longitude > -90)\n | ...........................................................................^
```

## Steps to Reproduce

```proto
syntax = "proto3";

import "google/type/latlng.proto";
import "buf/validate/validate.proto";

message TestMessage {
   google.type.LatLng coordinates = 6 [
      (buf.validate.field).cel = {
      id: 'coordinates',
      expression:
          "(this.latitude < 90 && this.latitude > -90) &&"
          "(this.longitude < 180 && this.longitude > -90)"
    }
  ];
}
```

## Expected Behavior

I can access normally nested values using `this.`

## Actual Behavior

Produces the error mentioned above:

```
unexpected failed resolution of 'google.type.LatLng
```

## Additional Context
It seems to be working if moving the validation to a message type validation instead of field. But it doesn't seem right to need to have it on the message since it's not accessing any other property outside the field itself

**Comment by rodaine** [comment]
Hi, @fenos! I'm sorry you're getting an unexpected error. I attempted to reproduce your issue in https://github.com/bufbuild/protovalidate-go/compare/rodaine/issue-174, but pv-go behaved as you'd expect. This also matches the conformance test [cases](https://github.com/bufbuild/protovalidate/blob/main/proto/protovalidate-testing/buf/validate/conformance/cases/custom_constraints/custom_constraints.proto) that [cover](https://github.com/bufbuild/protovalidate/blob/main/tools/protovalidate-conformance/internal/cases/cases_custom_constraints.go) this as well.

What version of pv-go are you using? If you're using buf for code generation, can you share your `buf.yaml` and `buf.gen.yaml`?

**Comment by fenos** [comment]
Hey @rodaine thanks a lot for checking this out. It is very strange that it is not working. Could it be because of some import order?

Versions I'm using:

```
connectrpc.com/validate v0.1.0
github.com/bufbuild/protovalidate-go v0.3.0 // indirect
```

Here are the bufs files:

**buf.yaml**
```yaml
# For details on buf.yaml configuration, visit https://buf.build/docs/configuration/v2/buf-yaml
version: v2
lint:
  use:
    - STANDARD
  except:
    - PACKAGE_DIRECTORY_MATCH
breaking:
  use:
    - FILE
deps:
  - buf.build/googleapis/googleapis:e93e34f48be043dab55be31b4b47f458
  - buf.build/bufbuild/protovalidate
```

**buf.gen.yaml**
```yaml
version: v2
plugins:
#   GO
  - local: protoc-gen-go
    out: gen/go/
    opt: paths=source_relative
  - local: protoc-gen-connect-go
    out: gen/go/
    opt: paths=source_relative

#   JS
  - local: protoc-gen-es
    out: gen/es/
    # Also generate any imported dependencies
    include_imports: true
    # Add more plugin options here
    opt: target=ts
  - local: protoc-gen-connect-query
    out: gen/es/
    opt: target=ts
```
