### ISSUE TITLE
Part of the validation code is not generated

### ISSUE THREAD

**Issue by dorlolo** [bufbuild/protovalidate-go#67]
## Description
I am testing the code in the 'example' directory. After using the 'buf generate proto' command, in the 'example.pb.validate.go' file, validation code has been generated for only a few fields. The validation code for fields like 'Id', 'Email', and 'Name' is empty. and the 'Home' field has not generated the primary validation code.
```go
func (m *Person) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Id

	// no validation rules for Email

	// no validation rules for Name

	if all {
		switch v := interface{}(m.GetHome()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, PersonValidationError{
					field:  "Home",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, PersonValidationError{
					field:  "Home",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetHome()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return PersonValidationError{
				field:  "Home",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if len(errors) > 0 {
		return PersonMultiError(errors)
	}

	return nil
}

```
this is my buf.gen.yaml :
```yaml
version: v1
managed:
  enabled: true
  go_package_prefix:
    default: tests.example.v1

plugins:
  - plugin: buf.build/protocolbuffers/go
    out: gen
    opt: paths=source_relative

  - plugin: buf.build/bufbuild/validate-go:v1.0.2
    out: gen
    opt:
      - paths=source_relative
```

## Environment

- **Operating System**:  Windows 11
- **Compiler/Toolchain**: go version go1.20.7 windows/amd64
- **Protobuf Compiler & Version**:  buf v1.27.1, protoc libprotoc 22.0-rc2
- **Protoc-gen-validate Version**: 1.0.2
- **Protovalidate Version**:  v1.0.2

## TestCode
[validatetest.zip](https://github.com/bufbuild/protovalidate-go/files/13110225/validatetest.zip)

**Comment by gopkg-dev** [comment]
buf.gen.yaml 

```yaml
version: v1
managed:
enabled: true
go_package_prefix:
default: tests.example.v1

plugins:

plugin: buf.build/protocolbuffers/go
out: gen
opt: paths=source_relative
```

https://github.com/bufbuild/protovalidate-go/blob/60a89b50e8dac2e86cdcc0cb401e9508f170c2be/README.md?plain=1#L9-L16

### example

https://github.com/bufbuild/protovalidate-go#example
