### ISSUE TITLE
[BUG] *.pb.validate.go Validate AND ValidateAll cannot use. 

### ISSUE THREAD

**Issue by FocusHuang** [bufbuild/protovalidate-go#93]
## Description

when i use - plugin: buf.build/bufbuild/validate-go to generate validation, a *.pb.validate.go is generated, but no validation rule in function Validate or ValidateAll. if i want to use validate, i need to new a protovalidateor to validate the struct. is it excessive?

## Steps to Reproduce

buf.gen.yaml
```yaml
version: v1
managed:
  enabled: false
plugins:
  # generate go struct code
  - plugin: buf.build/protocolbuffers/go
    out: .
    opt:
      - paths=source_relative
  # generate message validator code
  - plugin: buf.build/bufbuild/validate-go
    out: .
    opt:
      - paths=source_relative
```
```protobuf
message Task {
  int64 id = 1;
  string name = 2 [
    (buf.validate.field).required = true,
    (buf.validate.field).string = {min_len: 1}
  ];
  string description = 3 [
    (buf.validate.field).ignore_empty = true,
    (buf.validate.field).string = {min_len: 1}
  ];
}
```
task.pb.validate.go
```go
// Validate checks the field values on Task with the rules defined in the proto
// definition for this message. If any rules are violated, the first error
// encountered is returned, or nil if there are no violations.
func (m *Task) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on Task with the rules defined in the
// proto definition for this message. If any rules are violated, the result is
// a list of violation errors wrapped in TaskMultiError, or nil if none found.
func (m *Task) ValidateAll() error {
	return m.validate(true)
}

func (m *Task) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Id

	// no validation rules for Name

	// no validation rules for Description

	if len(errors) > 0 {
		return TaskMultiError(errors)
	}

	return nil
}
```

## Expected Behavior

i can use task.Validate() or task.ValidateAll() to validate fields

## Actual Behavior

all pass directly

## Environment

- **Operating System**: Linux
- **Version**: Ubuntu 22.04
- **Compiler/Toolchain**:  Buf
- **Protobuf Compiler & Version**: 
- **Protoc-gen-validate Version**:  
- **Protovalidate Version**:  e097f827e65240ac9fd4b1158849a8fc
- **BufVersion**: 1.28.1
